steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/csci5409-454215/k8s-assignment/container2:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/csci5409-454215/k8s-assignment/container2:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/container2-deployment', 'container2=us-central1-docker.pkg.dev/csci5409-454215/k8s-assignment/container2:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=k8s-assignment-cluster'
images:
- 'us-central1-docker.pkg.dev/csci5409-454215/k8s-assignment/container2:$COMMIT_SHA'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET