steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/csci5409-454215/k8s-assignment/container2:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/csci5409-454215/k8s-assignment/container2:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud container clusters get-credentials k8s-assignment-cluster --region us-central1
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=k8s-assignment-cluster'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    [
      'set', 'image',
      'deployment/container2-deployment',
      'container2=us-central1-docker.pkg.dev/csci5409-454215/k8s-assignment/container2:latest'
    ]
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=k8s-assignment-cluster'

images:
- 'us-central1-docker.pkg.dev/csci5409-454215/k8s-assignment/container2:latest'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET