---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: akshat-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
      - name: container1
        image: us-central1-docker.pkg.dev/csci5409-454215/k8s-assignment/container1:latest
        ports:
        - containerPort: 6000
        volumeMounts:
        - name: pv-storage
          mountPath: /akshat_PV_dir
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: akshat-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: container1-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 6000
  selector:
    app: container1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
      - name: container2
        image: us-central1-docker.pkg.dev/csci5409-454215/k8s-assignment/container2:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: pv-storage
          mountPath: /akshat_PV_dir
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: akshat-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: container2